apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  # tls:
  #   - hosts:
  #       - www.k8s-multi.com
  #     secretName: k8s-multi-com-tls
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
    - http:
        paths:
          - path: /api/*
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 5000
